export const FIELD_TYPES = {
  TEXT: 'TEXT',
  SELECT: 'SELECT',
  CHECKBOX: 'CHECKBOX',
};

export const SHORTCODE_TYPES = {
  IS_OPEN: 'IS_OPEN',
  OVERVIEW: 'OVERVIEW',
  HOLIDAYS: 'HOLIDAYS',
  IRREGULAR_OPENINGS: 'IRREGULAR_OPENINGS',
};
